management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      access: read_only
server:
  port: 8292

securitytokenservice:
  username: ${systembruker.username}
  password: ${systembruker.password}
  url: ${STSClientConfig}

## INTEGRASJONER ##
meldekortutbetalingsgrunnlag:
  v1:
    url: ${meldekortutbetalingsgrunnlag.v1.url}
oppdrag:
  service:
    url: ${oppdrag.service.url}
tilbakekreving:
  v1:
    url: ${tilbakekreving.v1.url}
