spring:
  config.import: vault://
  cloud:
    vault:
      reactive:
        enabled: false
      enabled: true
      uri: https://vault.adeo.no
      authentication: KUBERNETES
      kubernetes:
        role: fpwsproxy
        kubernetes-path: kubernetes/prod/fss
      kv:
        enabled: true
        backend: kv/prod/fss
        application-name: fpwsproxy/teamforeldrepenger
        default-context: fpwsproxy/teamforeldrepenger
