management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      enabled: false
server:
  port: 9010
spring:
  cloud:
    vault:
      enabled: false

no.nav.security.jwt:
  client:
    registration:
      fpfordel:
        well-known-url: http://localhost:8060/rest/v1/sts/.well-known/openid-configuration
        grant-type: client_credentials
        scope: openid
        authentication:
          client-id: fp-ws-proxy
          client-jwk: src/test/resources/tokenx/jwk.json
          client-auth-method: client_secret_post
      fpsak:
        well-known-url: http://localhost:8060/rest/v1/sts/.well-known/openid-configuration
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        authentication:
          client-id: fp-ws-proxy
          client-jwk: src/test/resources/tokenx/jwk.json
          client-auth-method: private_key_jwt
  issuer:
    sts-rs:
      discoveryurl: http://localhost:8060/rest/v1/sts/.well-known/openid-configuration
      accepted_audience: srvFPABAKUS, srvfpoppdrag, srvfptilbake
#    sts-ws: # TODO:
#      discoveryurl: http://localhost:8060/soap/SecurityTokenServiceProvider/
#      accepted_audience: srvGOSYS
securitytokenservice:
  username: vtp
  password: vtp
  url: http://localhost:8060/soap/SecurityTokenServiceProvider/
sts:
  username: vtp
  password: vtp
  baseUri: http://localhost:8060


## INTEGRASJONER ##
fpsak:
  baseUri: http://localhost:8080/fpsak
fpfordel:
  baseUri: http://localhost:8080/fpfordel
meldekortutbetalingsgrunnlag:
  v1:
    url: https://localhost:8063/soap/ail_ws/MeldekortUtbetalingsgrunnlag_v1
oppdrag:
  service:
    url: https://localhost:8063/soap/cics/services/oppdragService
tilbakekreving:
  v1:
    url: https://localhost:8063/soap/tilbakekreving/services/tilbakekrevingService
