management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      enabled: false
server:
  port: 8292
spring:
  cloud:
    vault:
      enabled: false

no.nav.security.jwt:
  issuer:
    sts-rs:
      discoveryurl: http://localhost:8060/rest/v1/sts/.well-known/openid-configuration
      accepted_audience: OIDC, vtp, srvfpabakus, srvfpoppdrag, srvfptilbake

securitytokenservice:
  username: vtp
  password: vtp
  url: http://localhost:8060/soap/SecurityTokenServiceProvider/
sts:
  username: vtp
  password: vtp
  baseUri: http://localhost:8060


## INTEGRASJONER ##
meldekortutbetalingsgrunnlag:
  v1:
    url: https://localhost:8063/soap/ail_ws/MeldekortUtbetalingsgrunnlag_v1
oppdrag:
  service:
    url: https://localhost:8063/soap/cics/services/oppdragService
tilbakekreving:
  v1:
    url: https://localhost:8063/soap/tilbakekreving/services/tilbakekrevingService
