management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      show-details : always
spring:
  mvc:
    log-request-details: true

# Brukes for entra discovery og jwks
entra:
  proxy: https://webproxy-nais.nav.no:8088

# Brukers av clientene på utgående kall (WS eller RS)
securitytokenservice:
  url: https://sts-q2.preprod.local/SecurityTokenServiceProvider/

## INTEGRASJONER ##
meldekortutbetalingsgrunnlag:
  v1:
    url: https://arena-q2.adeo.no/ail_ws/MeldekortUtbetalingsgrunnlag_v1
oppdrag:
  service:
    url: https://cics-q2.adeo.no/oppdrag/simulerFpServiceWSBinding
tilbakekreving:
  v1:
    url: https://cics-q2.adeo.no/oppdrag/K231CW80


