spring:
  config.import: vault://
  cloud:
    vault:
      reactive:
        enabled: false
      enabled: true
      uri: https://vault.adeo.no
      authentication: KUBERNETES
      kubernetes:
        role: fp-ws-proxy
        kubernetes-path: kubernetes/prod/fss
      kv:
        enabled: true
        backend: kv/prod/fss
        application-name: fp-ws-proxy/teamforeldrepenger
        default-context: fp-ws-proxy/teamforeldrepenger
## SIKKERHET ##
no.nav.security.jwt:
  client:
    registration:
      fpfordel:
        token-exchange:
          audience: prod-fss:teamforeldrepenger:fpfordel
      fpsak:
        token-exchange:
          audience: prod-fss:teamforeldrepenger:fpsak
