management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      access: read_only
server:
  port: 8292

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://vtp:8060/rest/azuread
          audiences: api://vtp, vtp, api://vtp.teamforeldrepenger.vtp/.default

securitytokenservice:
  username: vtp
  password: vtp
  url: http://localhost:8060/soap/SecurityTokenServiceProvider/

## INTEGRASJONER ##
meldekortutbetalingsgrunnlag:
  v1:
    url: https://localhost:8063/soap/ail_ws/MeldekortUtbetalingsgrunnlag_v1
oppdrag:
  service:
    url: https://localhost:8063/soap/cics/services/oppdragService
tilbakekreving:
  v1:
    url: https://localhost:8063/soap/tilbakekreving/services/tilbakekrevingService
