management:
  endpoint:
    health:
      show-details : never
  endpoints:
    web:
      exposure:
        include: env, configprops, info, health, metrics, prometheus
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
server:
  servlet:
    context-path: /fpwsproxy
spring:
  application:
    name: fpwsproxy
  mvc:
    log-request-details: true

## SIKKERHET ##
no.nav.security.jwt:
  issuer:
    sts-rs:
      discoveryurl: http://security-token-service.default/rest/v1/sts/.well-known/openid-configuration
      accepted_audience: srvfpabakus, srvfpoppdrag, srvfptilbake, srvk9-tilbake

# Brukers av klientene på utgående kall (WS eller RS)
securitytokenservice:
  username: ${systembruker.username}  # Kommer fra vault
  password: ${systembruker.password} # Kommer fra vault
  url: https://sts.adeo.no/SecurityTokenServiceProvider/

## INTEGRASJONER ##
meldekortutbetalingsgrunnlag:
  v1:
    url: https://arena.adeo.no/ail_ws/MeldekortUtbetalingsgrunnlag_v1

oppdrag:
  service:
    url: https://wasapp.adeo.no/cics/services/simulerFpServiceWSBinding

tilbakekreving:
  v1:
    url: https://cics.adeo.no/oppdrag/K231CW80



