management:
  endpoint:
    health:
      show-details : never
  endpoints:
    web:
      exposure:
        include: env, configprops, info, health, metrics, prometheus
server:
  servlet:
    context-path: /fpwsproxy
spring:
  main:
    banner-mode: off
  application:
    name: fpwsproxy
  mvc:
    log-request-details: true

# Mute deprecation warnings from Shibboleth libraries until wss4j later than 4.0.1 released
logging:
  level:
    DEPRECATED: ERROR

## SIKKERHET ##
no.nav.security.jwt:
  issuer:
    aad:
      discovery_url: ${azure.app.well.known.url}
      accepted_audience: api://${azure.app.client.id},${azure.app.client.id}
      proxy-url: http://webproxy.nais:8088

# Brukers av klientene på utgående kall (WS eller RS)
securitytokenservice:
  username: ${SYSTEMBRUKER_USERNAME}  # Kommer fra vault
  password: ${SYSTEMBRUKER_PASSWORD} # Kommer fra vault
  url: https://sts.adeo.no/SecurityTokenServiceProvider/

## INTEGRASJONER ##
meldekortutbetalingsgrunnlag:
  v1:
    url: https://arena.adeo.no/ail_ws/MeldekortUtbetalingsgrunnlag_v1

oppdrag:
  service:
    url: https://wasapp.adeo.no/cics/services/simulerFpServiceWSBinding

tilbakekreving:
  v1:
    url: https://cics.adeo.no/oppdrag/K231CW80



