management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      show-details : always
org:
  apache:
    cxf:
      logging:
        enable : true
spring:
  config.import: vault://
  cloud:
    vault:
      reactive:
        enabled: false
      enabled: true
      uri: https://vault.adeo.no
      authentication: KUBERNETES
      kubernetes:
        role: fp-ws-proxy
        kubernetes-path: kubernetes/preprod/fss
      kv:
        enabled: true
        backend: kv/preprod/fss
        application-name: fp-ws-proxy/teamforeldrepenger
        default-context: fp-ws-proxy/teamforeldrepenger


# Brukers av clientene på utgående kall (WS eller RS)
securitytokenservice:
  url: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
sts:
  uri: https://security-token-service.nais.preprod.local
