management:
  endpoint:
    health:
      show-details : never
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
  endpoints:
    web:
      exposure:
        include:  env, configprops, info, health, metrics, prometheus
  health :
    diskspace:
      enabled: false
    jms:
      enabled: false
server:
  servlet:
    context-path: /api
spring:
  application:
    name: fp-ws-proxy
  mvc:
    log-request-details: true

no.nav.security.jwt:
  client:
    registration:
      fpfordel:
        well-known-url: http://security-token-service.default/rest/v1/sts/.well-known/openid-configuration
        grant-type: client_credentials
        scope: openid
        authentication:
          client-id: ${token.x.client.id}
          client-jwk: ${token.x.private.jwk}
          client-auth-method: client_secret_post
      fpsak:
        well-known-url: http://security-token-service.default/rest/v1/sts/.well-known/openid-configuration
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        authentication:
          client-id: ${token.x.client.id}
          client-jwk: ${token.x.private.jwk}
          client-auth-method: private_key_jwt
  issuer:
    sts-rs:
      discoveryurl: http://security-token-service.default/rest/v1/sts/.well-known/openid-configuration
      accepted_audience: srvFPABAKUS, srvfpoppdrag, srvfptilbake
#    sts-ws: # TODO:
#      discoveryurl: https://sts.adeo.no/SecurityTokenServiceProvider/TODO/.well-known/openid-configuration
#      accepted_audience: srvGOSYS


# Brukers av klientene på utgående kall (WS eller RS)
securitytokenservice:
  username: ${securitytokenservice.username}  # Kommer fra vault
  password : ${securitytokenservice.password} # Kommer fra vault
  url: https://sts.adeo.no/SecurityTokenServiceProvider/

sts:
  username: ${securitytokenservice.username}  # Kommer fra vault
  password : ${securitytokenservice.password} # Kommer fra vault
  url: https://security-token-service.nais.adeo.no # TODO
