management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      show-details : always

org:
  apache:
    cxf:
      logging:
        enable : true

spring:
  config.import: vault://
  cloud:
    vault:
      reactive:
        enabled: false
      enabled: true
      uri: https://vault.adeo.no
      authentication: KUBERNETES
      kubernetes:
        role: fp-ws-proxy
        kubernetes-path: kubernetes/preprod/fss
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kv:
        application-name: fp-ws-proxy/teamforeldrepenger
        backend: kv/preprod/fss
        default-context: fp-ws-proxy/teamforeldrepenger

virksomhet:
  person:
    v3:
      endpointurl: https://app-q1.adeo.no/tpsws-aura/ws/Person/v3

securitytokenservice:
  url: https://sts-q1.preprod.local/SecurityTokenServiceProvider/

sts:
  uri: https://security-token-service.nais.preprod.local/rest/v1/sts/token?grant_type=client_credentials&scope=openid
