apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fpwsproxy
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  liveness:
    path: /fpwsproxy/actuator/health/liveness
    initialDelay: 5
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: /fpwsproxy/actuator/health/readiness
    initialDelay: 5
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: /fpwsproxy/actuator/prometheus
  resources:
    limits:
      cpu: "{{limits.cpu}}"
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: {{serviceuserkv}}
        mountPath: /var/run/secrets/nais.io/serviceuser/
  azure:
    application:
      enabled: true
  {{#if AZURE_IAC_RULES}}
  accessPolicy:
    inbound:
      rules:
      {{#each AZURE_IAC_RULES}}
      - application: {{app}}
        namespace: {{namespace}}
        cluster: {{cluster}}
        {{#if scopes}}
        permissions:
          scopes:
          {{#each scopes}}
            - "{{this}}"
          {{/each}}
        {{/if}}
      {{/each}}
  {{/if}}
