apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fp-ws-proxy
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  liveness:
    path: /api/actuator/health/liveness
    initialDelay: 15
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: /api/actuator/health/readiness
    initialDelay: 15
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: /api/actuator/prometheus
  resources:
    limits:
      cpu: "{{limits.cpu}}"
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  secureLogs:
    enabled: true
